#!/usr/bin/env python3
"""Convert GIF to zmk-niceview animation using PIL dithering.

Based on danielsodium/nice-view-gifs
"""

import argparse
import os
import re
import subprocess
import tempfile
from PIL import Image, ImageOps

# Default paths relative to this script
DEFAULT_ASSETS_DIR = "boards/shields/nice_oled/assets"
DEFAULT_CMAKE_PATH = "boards/shields/nice_oled/CMakeLists.txt"
DEFAULT_KCONFIG_PATH = "boards/shields/nice_oled/Kconfig.defconfig"
DEFAULT_ANIMATION_PATH = "boards/shields/nice_oled/widgets/animation.c"

def atkinson_dither(image, threshold=128):
    """Apply Atkinson dithering to a grayscale image."""
    pixels = image.load()
    width, height = image.size
    
    for y in range(height):
        for x in range(width):
            old_pixel = pixels[x, y]
            new_pixel = 255 if old_pixel > threshold else 0
            pixels[x, y] = new_pixel
            
            error = old_pixel - new_pixel
            
            # Distribute error to neighboring pixels (Atkinson pattern)
            # 1/8 error to each of 4 neighbors
            if x + 1 < width:
                pixels[x + 1, y] = min(255, max(0, pixels[x + 1, y] + error // 8))
            if x + 2 < width:
                pixels[x + 2, y] = min(255, max(0, pixels[x + 2, y] + error // 8))
            if y + 1 < height:
                if x > 0:
                    pixels[x - 1, y + 1] = min(255, max(0, pixels[x - 1, y + 1] + error // 8))
                pixels[x, y + 1] = min(255, max(0, pixels[x, y + 1] + error // 8))
                if x + 1 < width:
                    pixels[x + 1, y + 1] = min(255, max(0, pixels[x + 1, y + 1] + error // 8))
            if y + 2 < height:
                pixels[x, y + 2] = min(255, max(0, pixels[x, y + 2] + error // 8))
    
    return image

def process_frame(frame, target_width, target_height, threshold=128):
    """Process a frame with Atkinson dithering."""
    # Resize to fit within target dimensions
    original_width, original_height = frame.size
    scale = min(target_width / original_width, target_height / original_height)
    new_width = int(original_width * scale)
    new_height = int(original_height * scale)
    resized = frame.resize((new_width, new_height), Image.LANCZOS)
    
    # Convert to grayscale
    gray = resized.convert('L')
    
    # Apply Atkinson dithering
    dithered = atkinson_dither(gray, threshold)
    
    # Create output image (black background)
    output = Image.new('1', (target_width, target_height), 0)
    
    # Invert so white pixels become 1 (black on epaper) and black become 0 (white on epaper)
    inverted = ImageOps.invert(dithered)
    
    # Center the image
    x_offset = (target_width - new_width) // 2
    y_offset = (target_height - new_height) // 2
    output.paste(inverted, (x_offset, y_offset))
    
    return output

def create_animation_files(input_gif, output_c, output_h, name="shaymin", target_width=48, target_height=48, threshold=128):
    """Create C and H files for animation from GIF."""
    img = Image.open(input_gif)
    frame_count = img.n_frames
    
    # Generate C file
    c_content = f'''/* Generated using gif-convert.py */
/* Contains {frame_count} image(s). */
#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

'''
    
    # Add attribute guards
    for i in range(frame_count):
        frame_name = f"{name}_{i:02d}"
        c_content += f'''#ifndef LV_ATTRIBUTE_IMG_{frame_name.upper()}
#define LV_ATTRIBUTE_IMG_{frame_name.upper()}
#endif

'''
    
    # Process each frame
    for frame_idx in range(frame_count):
        img.seek(frame_idx)
        frame = img.convert('RGB')
        
        # Apply Atkinson dithering
        processed = process_frame(frame, target_width, target_height, threshold)
        
        # Get frame data
        frame_data = processed.tobytes()
        data_size = len(frame_data) + 8
        
        frame_name = f"{name}_{frame_idx:02d}"
        
        c_content += f'''// Autogenerated map from frame {frame_idx}
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_{frame_name.upper()} uint8_t {frame_name}_map[] = {{
#if CONFIG_NICE_OLED_WIDGET_INVERTED
  0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
  0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
  0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
  0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

'''
        
        # Write frame data
        for i, byte in enumerate(frame_data):
            if i % 16 == 0:
                c_content += "    "
            c_content += f"0x{byte:02X}, "
            if (i + 1) % 16 == 0:
                c_content += "\n"
        if len(frame_data) % 16 != 0:
            c_content += "\n"
        
        c_content += f'''}};

const lv_img_dsc_t {frame_name} = {{
  .header.cf = LV_IMG_CF_INDEXED_1BIT,
  .header.always_zero = 0,
  .header.reserved = 0,
  .header.w = {target_width},
  .header.h = {target_height},
  .data_size = {data_size},
  .data = {frame_name}_map,
}};

'''
    
    # Generate H file
    h_content = f'''#ifndef {name.upper()}_IMAGES_H
#define {name.upper()}_IMAGES_H
#ifdef __cplusplus
extern "C" {{
#endif
#include "lvgl.h"
// -------- Image Descriptors Declarations --------
'''
    
    for i in range(frame_count):
        frame_name = f"{name}_{i:02d}"
        h_content += f'LV_IMG_DECLARE({frame_name});\n'
    
    h_content += f'''
// -------- Array of Pointers to Image Descriptors --------
const lv_img_dsc_t *{name}_images[{frame_count}] = {{
'''
    
    for i in range(frame_count):
        frame_name = f"{name}_{i:02d}"
        h_content += f'    &{frame_name},\n'
    
    h_content += f'''}};

#define {name.upper()}_IMAGES_NUM_IMAGES {frame_count}

#ifdef __cplusplus
}} /* extern "C" */
#endif
#endif /* {name.upper()}_IMAGES_H */
'''
    
    # Write files
    with open(output_c, 'w') as f:
        f.write(c_content)
    
    with open(output_h, 'w') as f:
        f.write(h_content)
    
    return frame_count

def preprocess_gif_with_imagemagick(input_gif, output_gif, crop=None, rotate=None, center=False):
    """Preprocess GIF using ImageMagick to coalesce frames and convert to grayscale.
    
    Args:
        input_gif: Path to input GIF file
        output_gif: Path for preprocessed output
        crop: Optional crop geometry (e.g., "48x48" or "48x48+16+16")
        rotate: Optional rotation angle in degrees (default: None)
        center: Whether to center the crop using -gravity center (default: False)
    
    The order of operations is: coalesce → rotate → colorspace Gray → gravity center → crop → +repage
    """
    try:
        cmd = [
            "magick",
            input_gif,
            "-coalesce",
        ]
        
        # Add rotation if specified
        if rotate is not None:
            cmd.extend(["-rotate", str(rotate)])
        
        # Convert to grayscale
        cmd.extend(["-colorspace", "Gray"])
        
        # Add gravity center BEFORE crop if center is requested
        if center:
            cmd.extend(["-gravity", "center"])
        
        # Add crop if specified (must come after gravity for centering to work)
        if crop:
            # If crop doesn't include offset, add +0+0
            if '+' not in crop:
                cmd.extend(["-crop", f"{crop}+0+0"])
            else:
                cmd.extend(["-crop", crop])
            cmd.append("+repage")
        
        cmd.append(output_gif)
        
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"ImageMagick error: {e.stderr}")
        return False
    except FileNotFoundError:
        print("ImageMagick 'magick' command not found. Please install ImageMagick.")
        return False


def register_in_animation_c(name, frame_count, animation_path=DEFAULT_ANIMATION_PATH):
    """Register animation in animation.c file.
    
    Adds LV_IMG_DECLARE declarations and the image array.
    """
    if not os.path.exists(animation_path):
        print(f"Warning: {animation_path} not found, skipping registration")
        return False
    
    with open(animation_path, 'r') as f:
        content = f.read()
    
    # Check if already registered
    if f"LV_IMG_DECLARE({name}_00)" in content:
        print(f"Animation '{name}' already registered in animation.c")
        return True
    
    name_upper = name.upper()
    
    # Generate LV_IMG_DECLARE block
    declares = "\n".join([f"LV_IMG_DECLARE({name}_{i:02d});" for i in range(frame_count)])
    
    # Generate image array
    # Wrap to 7 items per line like the existing code
    wrapped_items = []
    for i in range(0, frame_count, 7):
        chunk = ", ".join([f"&{name}_{j:02d}" for j in range(i, min(i + 7, frame_count))])
        wrapped_items.append(f"    {chunk}")
    array_content = ",\n".join(wrapped_items)
    
    declare_block = f'''
#elif IS_ENABLED(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_{name_upper})
{declares}

const lv_img_dsc_t *{name}_imgs[] = {{
{array_content}
}};
'''
    
    # Find the #else/#endif after pokemon block (or spaceman as fallback)
    # Pattern: look for #else followed by #endif after the last animation
    patterns = [
        r'(const lv_img_dsc_t \*pokemon_imgs\[\].*?\n\};)\n(#else)\n(#endif)',
        r'(const lv_img_dsc_t \*spaceman_imgs\[\].*?\n\};)\n(#elif)',
        r'(const lv_img_dsc_t \*cat_imgs\[\].*?\n\};)\n(#elif)',
    ]
    
    match = None
    for pattern in patterns:
        match = re.search(pattern, content, re.DOTALL)
        if match:
            break
    
    if match:
        # Insert between the array definition and #else
        insert_pos = match.end(1)
        new_content = content[:insert_pos] + declare_block + content[insert_pos:]
    else:
        # Fallback: find the #else at the end of the peripheral animations block
        pattern = r'(#else)\n(#endif)\n(#else // IS_ENABLED\(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL\))'
        match = re.search(pattern, content)
        if match:
            insert_pos = match.start(1)
            new_content = content[:insert_pos] + declare_block + content[insert_pos:]
        else:
            print("Warning: Could not find insertion point in animation.c")
            return False
    
    # Also add to draw_animation function - find the pokemon block and add before #else
    # Pattern: look for lv_animimg_set_src for pokemon followed by #else
    draw_patterns = [
        r'(elif IS_ENABLED\(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON\)\s+lv_animimg_set_src\(art, \(const void \*\*\)pokemon_imgs, \d+\);)\n(#else)',
        r'(elif IS_ENABLED\(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN\)\s+lv_animimg_set_src\(art, \(const void \*\*\)spaceman_imgs, \d+\);)\n(#elif)',
    ]
    
    for pattern in draw_patterns:
        match = re.search(pattern, new_content)
        if match:
            draw_line = f'\n#elif IS_ENABLED(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_{name_upper})\n    lv_animimg_set_src(art, (const void **){name}_imgs, {frame_count});'
            insert_pos = match.end(1)
            new_content = new_content[:insert_pos] + draw_line + new_content[insert_pos:]
            break
    
    with open(animation_path, 'w') as f:
        f.write(new_content)
    
    print(f"Registered '{name}' in {animation_path}")
    return True


def register_in_cmake(name, cmake_path=DEFAULT_CMAKE_PATH):
    """Register animation in CMakeLists.txt file.
    
    Adds target_sources_ifdef for the new asset.
    """
    if not os.path.exists(cmake_path):
        print(f"Warning: {cmake_path} not found, skipping registration")
        return False
    
    with open(cmake_path, 'r') as f:
        content = f.read()
    
    # Check if already registered
    if f"CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_{name.upper()}" in content:
        print(f"Animation '{name}' already registered in CMakeLists.txt")
        return True
    
    # Find the pokemon line (last animation) and add after it
    # Or use spaceman or cat as fallback
    patterns = [
        r'(target_sources_ifdef\(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON app PRIVATE assets/pokemon\.c\))',
        r'(target_sources_ifdef\(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN app PRIVATE assets/spaceman\.c\))',
        r'(target_sources_ifdef\(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT app PRIVATE assets/cat\.c\))',
    ]
    
    match = None
    for pattern in patterns:
        match = re.search(pattern, content)
        if match:
            break
    
    if match:
        name_upper = name.upper()
        new_line = f'\n      target_sources_ifdef(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_{name_upper} app PRIVATE assets/{name}.c)'
        insert_pos = match.end()
        new_content = content[:insert_pos] + new_line + content[insert_pos:]
        
        with open(cmake_path, 'w') as f:
            f.write(new_content)
        
        print(f"Registered '{name}' in {cmake_path}")
        return True
    else:
        print("Warning: Could not find insertion point in CMakeLists.txt")
        return False


def register_in_kconfig(name, default_ms=5000, kconfig_path=DEFAULT_KCONFIG_PATH):
    """Register animation in Kconfig.defconfig file.
    
    Adds config option and animation duration default.
    """
    if not os.path.exists(kconfig_path):
        print(f"Warning: {kconfig_path} not found, skipping registration")
        return False
    
    with open(kconfig_path, 'r') as f:
        content = f.read()
    
    # Check if already registered
    if f"NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_{name.upper()}" in content:
        print(f"Animation '{name}' already registered in Kconfig.defconfig")
        return True
    
    name_upper = name.upper()
    name_cap = name.capitalize()
    
    # Find an existing animation config block to insert after
    # Try pokemon first, then spaceman, then cat as fallbacks
    config_patterns = [
        r'(config NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON\s+bool "Enable pokemon animation on peripheral"\s+default n)',
        r'(config NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN\s+bool "Enable spaceman animation on peripheral"\s+default n)',
        r'(config NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT\s+bool "Enable cat animation on peripheral"\s+default y)',
    ]
    
    match = None
    for pattern in config_patterns:
        match = re.search(pattern, content)
        if match:
            break
    
    if match:
        config_block = f'''

config NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_{name_upper}
    bool "Enable {name_cap} animation on peripheral"
    default n
'''
        insert_pos = match.end()
        new_content = content[:insert_pos] + config_block + content[insert_pos:]
        
        # Also add the animation duration default
        # Find a default line for animation duration
        ms_patterns = [
            r'(default \d+ if NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON)',
            r'(default \d+ if NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN)',
            r'(default \d+ if NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT)',
        ]
        
        ms_match = None
        for pattern in ms_patterns:
            ms_match = re.search(pattern, new_content)
            if ms_match:
                break
        
        if ms_match:
            ms_line = f'\n    default {default_ms} if NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_{name_upper}'
            insert_pos = ms_match.end()
            new_content = new_content[:insert_pos] + ms_line + new_content[insert_pos:]
        
        with open(kconfig_path, 'w') as f:
            f.write(new_content)
        
        print(f"Registered '{name}' in {kconfig_path}")
        return True
    else:
        print("Warning: Could not find insertion point in Kconfig.defconfig")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Convert GIF to zmk-niceview animation using Atkinson dithering."
    )
    parser.add_argument(
        "input_gif",
        help="Path to the input GIF file"
    )
    parser.add_argument(
        "-n", "--name",
        help="Base name for output files (default: derived from GIF filename without extension)",
        default=None
    )
    parser.add_argument(
        "-o", "--output-dir",
        help="Output directory for generated .c and .h files (default: boards/shields/nice_oled/assets)",
        default="boards/shields/nice_oled/assets"
    )
    parser.add_argument(
        "-W", "--width",
        type=int,
        default=64,
        help="Target width in pixels (default: 64)"
    )
    parser.add_argument(
        "-H", "--height",
        type=int,
        default=64,
        help="Target height in pixels (default: 64)"
    )
    parser.add_argument(
        "-t", "--threshold",
        type=int,
        default=128,
        help="Dithering threshold (0-255, default: 128)"
    )
    parser.add_argument(
        "--no-preprocess",
        action="store_true",
        help="Skip ImageMagick preprocessing (useful if GIF is already preprocessed)"
    )
    parser.add_argument(
        "--crop",
        help="Crop geometry for ImageMagick (e.g., '48x48' or '48x48+16+16')"
    )
    parser.add_argument(
        "--rotate",
        type=int,
        default=90,
        help="Rotation angle in degrees for ImageMagick (default: 90)"
    )
    parser.add_argument(
        "--no-rotate",
        action="store_true",
        help="Disable rotation (overrides --rotate)"
    )
    parser.add_argument(
        "--center",
        action="store_true",
        help="Center the image after cropping using -gravity center"
    )
    parser.add_argument(
        "--animation-ms",
        type=int,
        default=5000,
        help="Animation duration in milliseconds for Kconfig (default: 5000)"
    )
    parser.add_argument(
        "--no-register",
        action="store_true",
        help="Skip registering the animation in animation.c, CMakeLists.txt, and Kconfig.defconfig"
    )
    
    args = parser.parse_args()
    
    # Derive name from filename if not provided
    name = args.name
    if name is None:
        name = os.path.splitext(os.path.basename(args.input_gif))[0]
    
    input_gif = args.input_gif
    output_dir = args.output_dir
    
    # Preprocess with ImageMagick unless skipped
    if not args.no_preprocess:
        print(f"Preprocessing {input_gif} with ImageMagick...")
        with tempfile.NamedTemporaryFile(suffix=".gif", delete=False) as tmp:
            tmp_path = tmp.name
        # Determine rotation: use args.rotate unless --no-rotate is specified
        rotate_value = None if args.no_rotate else args.rotate
        if preprocess_gif_with_imagemagick(input_gif, tmp_path, crop=args.crop, rotate=rotate_value, center=args.center):
            input_gif = tmp_path
            print("Preprocessing complete.")
        else:
            print("Preprocessing failed, using original GIF.")
    
    print(f"Processing {input_gif}...")
    count = create_animation_files(
        input_gif,
        os.path.join(output_dir, f"{name}.c"),
        os.path.join(output_dir, f"{name}.h"),
        name=name,
        target_width=args.width,
        target_height=args.height,
        threshold=args.threshold
    )
    print(f"Generated {count} frames")
    print(f"Output files: {os.path.join(output_dir, name)}.c, {os.path.join(output_dir, name)}.h")
    
    # Clean up temp file if it was created
    if not args.no_preprocess and 'tmp_path' in locals() and os.path.exists(tmp_path):
        os.unlink(tmp_path)
    
    # Register the animation in project files unless skipped
    if not args.no_register:
        print("\nRegistering animation in project files...")
        register_in_animation_c(name, count)
        register_in_cmake(name)
        register_in_kconfig(name, args.animation_ms)


if __name__ == "__main__":
    main()